[package]
name = "third_person_controller"

edition = "2021"
publish = false
version = "0.0.1"

[dependencies]
ambient_api = { workspace = true }

[build-dependencies]
ambient_package_projection = { workspace = true }

[[bin]]
name = "client_third_person_controller"
path = "src/client.rs"
required-features = ["client"]

[[bin]]
name = "server_third_person_controller"
path = "src/server.rs"
required-features = ["server"]

[features]
client = ["ambient_api/client"]
server = ["ambient_api/server"]
