[package]
id = "roosvvawp6sjvlolokk5qyafl5vp2su7"
name = "Tangent Spawner: Vehicle"
description = "Handles vehicle spawning for Tangent."
version = "0.3.2-nightly-2024-01-11"
content = { type = "Asset", code = true }
ambient_version = "0.3.2-nightly-2024-01-11"
authors = ["philpax"]

[dependencies]
tangent_schema = { path = "../../schema", id = "mwrcsok65na7owrbdococ5sthr3ccskc", version = "0.3.2-nightly-2024-01-11" }

nameplates = { path = "../../../../std/nameplates", id = "per6j2iqhj3jz4da3fqr75jcj2kqjooo", version = "0.3.2-nightly-2024-01-11" }

[messages.VehicleSpawn]
name = "Vehicle Spawn"
description = "Spawns the vehicle from the given definition."
fields = { def_id = "EntityId", position = "Vec3", rotation = { container_type = "Option", element_type = "Quat" }, driver_id = { container_type = "Option", element_type = "EntityId" } }
