[package]
id = "hs7ygpw4pmpsixtcohdcvzxwmrfzubvi"
name = "Tangent UI: Class Selection"
description = "Implements the class selection UI."
version = "0.3.2-nightly-2024-01-11"
content = { type = "Asset", code = true }
ambient_version = "0.3.2-nightly-2024-01-11"
authors = ["philpax"]

[dependencies]
tangent_schema = { path = "../../schema", id = "mwrcsok65na7owrbdococ5sthr3ccskc", version = "0.3.2-nightly-2024-01-11" }

[messages.ClassSetRequest]
description = "Sent by the client to request a class set change."
fields = { class_id = "EntityId" }
