disallowed-macros = [
    # { path = "std::eprintln", reason = "prefer tracing over raw stdout" },
    # { path = "std::println", reason = "prefer tracing over raw stdout" },
    { path = "std::dbg", reason = "prefer tracing over raw stdout" },

    # We would like to prevent todos without reason, but there doesn't appear to be a way to do this right now.
    # { path = "std::todo", reason = "Using `todo` is not informative" },
]
disallowed-types = [
    { path = "std::time::Instant", reason = "time is not implemented on wasm" },
    { path = "std::time::SystemTime", reason = "time is not implemented on wasm" },
]

disallowed-methods = [
    { path = "ulid::Ulid::new", reason = "panics on wasm: https://github.com/dylanhart/ulid-rs/issues/52" },
]

allow-dbg-in-tests = true
