[package]
id = "t33j53muycmj4i66en5lheneowad5hbz"
name = "Dependencies (Code)"
version = "0.3.2-nightly-2024-01-11"
content = { type = "Asset", code = true }
ambient_version = "0.3.2-nightly-2024-01-11"

[dependencies]
ambient_example_deps_assets = { path = "../assets" , id = "viyiawgsl5lsiul6pup6pyv6bbt6o3vw", version = "0.3.2-nightly-2024-01-11" }

[components]
spawned_by_us = { type = "Empty" }
spin_direction = { type = "ambient_example_deps_assets::SpinDirection" }

[messages.Spawn]
name = "Spawn"
description = "Spawn the asset."
[messages.Spawn.fields]
spin_speed = "F32"
spin_direction = "ambient_example_deps_assets::SpinDirection"
