[package]
id = "nd2mwrslb3iyo2bw4jmwcbkuo4mtuyfr"
name = "Decals"
description = "Render 'stickers' onto any surface."
version = "0.3.2-nightly-2024-01-11"
repository = "https://github.com/AmbientRun/Ambient/tree/main/guest/rust/examples/basics/decals"
type = "Game"
content = { type = "Playable", example = true }
ambient_version = "0.3.2-nightly-2024-01-11"

[dependencies]
orbit_camera = { path = "../../../packages/std/orbit_camera" , id = "tijz7x6fimbgu24sbbtp4nllhfxbgblp", version = "0.3.2-nightly-2024-01-11" }
