tests = [
    "examples/basics/input",
    "examples/basics/primitives",

    "examples/intermediate/async",
    "examples/intermediate/messaging",

    "examples/controllers/first_person_camera",
    # This is flaky currently (see #973), so disabling until we can figure out a better way to do it
    # "examples/controllers/third_person_camera",

    "examples/assets/basic_model",
    "examples/assets/material_overriding",
    # Secretes aren't passed to external PRs so we can't download the assets for this for PRs
    # "examples/assets/unity",

    "examples/physics/visualize_colliders",

    "examples/rendering/decals",
    "examples/rendering/fog",
    "examples/rendering/image",
    "examples/rendering/line",
    "examples/rendering/raw_text",
    "examples/rendering/samplers",
    "examples/rendering/procedural_generation",
    "examples/rendering/transparency",

    "examples/ui/auto_editor",
    "examples/ui/button",
    "examples/ui/dock_layout",
    "examples/ui/editors",
    "examples/ui/flow_layout",
    "examples/ui/image",
    "examples/ui/rect",
    "examples/ui/screens",
    "examples/ui/slider",
    "examples/ui/text",

    "packages/games/tictactoe",
    "packages/games/arkanoid",
]
