[package]
name = "afps_world_latency"

edition = "2021"
publish = false
version = "0.0.1"

[dependencies]
ambient_api = { workspace = true }

[build-dependencies]
ambient_package_projection = { workspace = true }

[[bin]]
name = "world_latency_client"
path = "src/client.rs"
required-features = ["client"]

[[bin]]
name = "world_latency_server"
path = "src/server.rs"
required-features = ["server"]

[features]
client = ["ambient_api/client"]
server = ["ambient_api/server"]
