
[package]
name = "ambient_element_component"
edition = "2021"
description = "Helper procedural macro for the Ambient runtime that converts a function to an `ElementComponent`, allowing for more concise definitions of components."
license = "MIT OR Apache-2.0"
repository = "https://github.com/AmbientRun/Ambient"
rust-version = { workspace = true }
version = { workspace = true }

[lib]
proc-macro = true

[dependencies]
proc-macro2 = { workspace = true }
quote = { workspace = true }
itertools = { workspace = true }
syn = { workspace = true }
