[package]
name = "dioxus_example"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dioxus = "0.3.2"
dioxus-web = "0.3.1"
ambient_web = { path = "../client" }
web-sys = { version = "0.3.61", features = ["Window", "Document", "Element"] }
wasm-bindgen = { workspace = true }
serde-wasm-bindgen.workspace = true
