[package]
name = "ambient_package_projection"
version = { workspace = true }
rust-version = { workspace = true }
edition = "2021"
description = "Generates a projected representation of your Ambient package and its dependencies for use in your Rust code."
license = "MIT OR Apache-2.0"
documentation = "https://docs.rs/ambient_package_projection"
repository = "https://github.com/AmbientRun/Ambient"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
quote = "1.0"
proc-macro2 = "1.0"

ambient_package_macro_common = { workspace = true }

anyhow = { workspace = true }

syn = { version = "1.0", features = ["full"] }
tokio = { version = "1.0", features = ["full"] }
