[package]
id = "solyomvjgvfpd7x2k6a6xiajzynxfmex"
name = "Sun"
description = "Create a sun and sky."
version = "0.3.2-nightly-2024-01-11"
repository = "https://github.com/AmbientRun/Ambient/tree/main/guest/rust/examples/basics/sun"
type = "Game"
content = { type = "Playable", example = true }
ambient_version = "0.3.2-nightly-2024-01-11"

[dependencies]
orbit_camera = { path = "../../../packages/std/orbit_camera", id = "tijz7x6fimbgu24sbbtp4nllhfxbgblp", version = "0.3.2-nightly-2024-01-11" }
