[package]
name = "ambient_example_messaging"

edition = "2021"
publish = false
rust-version = { workspace = true }
version = { workspace = true }

[dependencies]
ambient_api = { workspace = true }

[build-dependencies]
ambient_package_projection = { workspace = true }

[[bin]]
name = "client_messaging"
path = "src/client.rs"
required-features = ["client"]

[[bin]]
name = "client_messaging_two"
path = "src/client_two.rs"
required-features = ["client"]

[[bin]]
name = "server_messaging"
path = "src/server.rs"
required-features = ["server"]

[[bin]]
name = "server_messaging_two"
path = "src/server_two.rs"
required-features = ["server"]

[features]
client = ["ambient_api/client"]
server = ["ambient_api/server"]
