[[pipelines]]
sources = ["quad-nearest.glb"]
type = "Models"

[[pipelines.material_overrides]]

[pipelines.material_overrides.filter]
type = "ByName"
name = "Material"

[pipelines.material_overrides.material]
base_color = "checkerboard.png"

[pipelines.material_overrides.material.sampler]
address_mode_u = "clamp-to-edge"
address_mode_v = "clamp-to-edge"
address_mode_w = "clamp-to-edge"
mag_filter = "nearest"
min_filter = "nearest"
mipmap_filter = "nearest"

[[pipelines]]
sources = ["quad-linear.glb"]
type = "Models"

[[pipelines.material_overrides]]

[pipelines.material_overrides.filter]
type = "ByName"
name = "Material"

[pipelines.material_overrides.material]
base_color = "checkerboard.png"

[pipelines.material_overrides.material.sampler]
address_mode_u = "clamp-to-edge"
address_mode_v = "clamp-to-edge"
address_mode_w = "clamp-to-edge"
mag_filter = "linear"
min_filter = "linear"
mipmap_filter = "linear"
