[package]
id = "viyiawgsl5lsiul6pup6pyv6bbt6o3vw"
name = "Dependencies (Assets)"
version = "0.3.2-nightly-2024-01-11"
content = { type = "Asset", models = true }
ambient_version = "0.3.2-nightly-2024-01-11"

[components]
spin_speed = { type = "F32", name = "Spin speed" }

[enums.SpinDirection]
description = "The direction the cube should spin"
[enums.SpinDirection.members]
Forward = "Forward"
Backward = "Backward"
