[package]
id = "jkfalriqol5mtd7hxq7yssldubgpcf5o"
name = "animations"
version = "0.3.2-nightly-2024-01-11"
content = { type = "Playable", example = true }
ambient_version = "0.3.2-nightly-2024-01-11"

[dependencies]
base_assets = { path = "../../../packages/std/base_assets", id = "n7a4j7htvenss35tsnfvegbhxuwij5il", version = "0.3.2-nightly-2024-01-11" }
character_animation = { path = "../../../packages/std/character_animation", id = "d3y3wbexrclipsykysumem3fthkudwx2", version = "0.3.2-nightly-2024-01-11" }
orbit_camera = { path = "../../../packages/std/orbit_camera", id = "tijz7x6fimbgu24sbbtp4nllhfxbgblp", version = "0.3.2-nightly-2024-01-11" }
performance_bar = { path = "../../../packages/tools/performance_bar", id = "kekdhmfpksiukzcvawellrsn5eeevjfd", version = "0.3.2-nightly-2024-01-11" }
