[package]
name = "performance_bar"

edition = "2021"
publish = false
rust-version = { workspace = true }
version = { workspace = true }

[dependencies]
ambient_api = { workspace = true }

[build-dependencies]
ambient_package_projection = { workspace = true }

[[bin]]
name = "performance_bar_client"
path = "src/client.rs"
required-features = ["client"]

[features]
client = ["ambient_api/client"]
server = ["ambient_api/server"]
