[package]
name = "package_manager"

edition = "2021"
publish = false
version = "0.0.1"

[dependencies]
ambient_api = { workspace = true }
ambient_package = { workspace = true }
ambient_shared_types = { workspace = true }
ambient_color = { workspace = true }
ambient_brand_theme = { workspace = true }

itertools = "0.11"
toml = "0.7"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

[build-dependencies]
ambient_package_projection = { workspace = true }

[[bin]]
name = "package_manager_client"
path = "src/client_bin.rs"
required-features = ["client"]

[[bin]]
name = "package_manager_server"
path = "src/server_bin.rs"
required-features = ["server"]

[features]
client = ["ambient_api/client"]
server = ["ambient_api/server"]
