[package]
description = "The API to the Ambient Runtime"
documentation = "https://docs.rs/ambient_api"
edition = "2021"
license = "MIT OR Apache-2.0"
name = "ambient_api"
repository = "https://github.com/AmbientRun/Ambient"
rust-version = { workspace = true }
version = { workspace = true }

[package.metadata.docs.rs]
# https://stackoverflow.com/a/61417700
all-features = true
rustdoc-args = ["--cfg", "docsrs"]
targets = ["wasm32-wasi"]

[dependencies]
ambient_api_core = { workspace = true }
ambient_ui = { workspace = true }
ambient_element = { workspace = true }
ambient_cb = { workspace = true }
ambient_editor_derive = { workspace = true }

anyhow = { workspace = true }
futures = { workspace = true }
once_cell = { workspace = true }
rand = { workspace = true }
glam = { workspace = true }
ordered-float = { workspace = true }

[features]
client = [
    "ambient_api_core/client",
    "ambient_ui/client",
    "ambient_element/guest",
]
server = [
    "ambient_api_core/server",
    "ambient_ui/server",
    "ambient_element/guest",
]
