[package]
id = "mnm43qv33k7kx235bz5hcgoguokwxzwo"
name = "Tangent Behavior: Vehicle"
description = "Implements the vehicle behavior for Tangent."
version = "0.3.2-nightly-2024-01-11"
content = { type = "Asset", code = true }
ambient_version = "0.3.2-nightly-2024-01-11"
authors = ["philpax"]

[dependencies]
tangent_schema = { path = "../../schema", id = "mwrcsok65na7owrbdococ5sthr3ccskc", version = "0.3.2-nightly-2024-01-11" }
game_object = { path = "../../../../schemas/game_object", id = "hvxms7i2px7krvkm23sxfjxsjqlcmtb5", version = "0.3.2-nightly-2024-01-11" }
kenney_impact_sounds = { path = "../../../../assets/kenney_impact_sounds", id = "e4unr4x2lz2ov7dsd5vnjylbykwixvv2", version = "0.3.2-nightly-2024-01-11" }
explosion = { path = "../../../../std/explosion", id = "cneomdouziieskjvs3szwmigzotofjzs", version = "0.3.2-nightly-2024-01-11" }

[messages.OnCollision]
name = "On Collision"
description = "Sent to the client when a vehicle collides with something."
fields = { position = "Vec3", speed = "F32", vehicle_id = "EntityId" }
