[package]
name = "tangent_behavior_vehicle"

edition = "2021"
publish = false
rust-version = { workspace = true }
version = { workspace = true }

[dependencies]
ambient_api = { workspace = true }

[build-dependencies]
ambient_package_projection = { workspace = true }

[[bin]]
name = "tangent_behavior_vehicle_client"
path = "src/client.rs"
required-features = ["client"]

[[bin]]
name = "tangent_behavior_vehicle_server"
path = "src/server.rs"
required-features = ["server"]

[features]
client = ["ambient_api/client"]
server = ["ambient_api/server"]
