[package]
name = "ambient_schema"
version = { workspace = true }
rust-version = { workspace = true }
edition = "2021"
description = "Ambient schema."
license = "MIT OR Apache-2.0"
repository = "https://github.com/AmbientRun/Ambient"
include = ["**/*"]

[dependencies]
