[package]
description = "The API to the Ambient Runtime (core)"
documentation = "https://docs.rs/ambient_api_core"
edition = "2021"
license = "MIT OR Apache-2.0"
name = "ambient_api_core"
repository = "https://github.com/AmbientRun/Ambient"
rust-version = { workspace = true }
version = { workspace = true }

[package.metadata.docs.rs]
# https://stackoverflow.com/a/61417700
all-features = true
rustdoc-args = ["--cfg", "docsrs"]
targets = ["wasm32-wasi"]

[dependencies]
ambient_api_macros = { workspace = true }
ambient_shared_types = { workspace = true }
ambient_package_rt = { workspace = true }

anyhow = { workspace = true }
byteorder = { workspace = true }
data-encoding = { workspace = true }
futures = { workspace = true }
once_cell = { workspace = true }
paste = { workspace = true }
thiserror = { workspace = true }
rand = { workspace = true }
glam = { workspace = true }
wit-bindgen = { workspace = true }
ulid = { workspace = true }
indexmap = { workspace = true }
serde = { workspace = true }

[features]
client = []
server = []
