[package]
name = "tangent_camera_follow"

edition = "2021"
publish = false
version = "0.1.0"

[dependencies]
ambient_api = { workspace = true }

[build-dependencies]
ambient_package_projection = { workspace = true }

[[bin]]
name = "tangent_camera_follow_client"
path = "src/client.rs"
required-features = ["client"]

[features]
client = ["ambient_api/client"]
server = ["ambient_api/server"]
