[package]
id = "pfzpi7ypoegwizizej5ojfcsncqa4bet"
name = "First-person camera"
description = "A simple FPS camera and input example."
version = "0.3.2-nightly-2024-01-11"
repository = "https://github.com/AmbientRun/Ambient/tree/main/guest/rust/examples/basics/first_person_camera"
type = "Game"
content = { type = "Playable", example = true }
ambient_version = "0.3.2-nightly-2024-01-11"


[dependencies]
base_assets = { path = "../../../packages/std/base_assets", id = "n7a4j7htvenss35tsnfvegbhxuwij5il", version = "0.3.2-nightly-2024-01-11" }
third_person_controller = { path = "../../../packages/std/third_person_controller", id = "vuph6dqdj6li4apmcgomn3faudcbfz56", version = "0.3.2-nightly-2024-01-11" }
character_animation = { path = "../../../packages/std/character_animation", id = "d3y3wbexrclipsykysumem3fthkudwx2", version = "0.3.2-nightly-2024-01-11" }
hide_cursor = { path = "../../../packages/std/hide_cursor", id = "xar372tfo2oswb4pkvx7h7o3rxi6tap6", version = "0.3.2-nightly-2024-01-11" }
