[package]
name = "ambient_example_first_person_camera"

edition = "2021"
publish = false
rust-version = { workspace = true }
version = { workspace = true }

[dependencies]
ambient_api = { workspace = true }

[build-dependencies]
ambient_package_projection = { workspace = true }

[[bin]]
name = "client_first_person_camera"
path = "src/client.rs"
required-features = ["client"]

[[bin]]
name = "server_first_person_camera"
path = "src/server.rs"
required-features = ["server"]

[features]
client = ["ambient_api/client"]
server = ["ambient_api/server"]
