[package]
name = "ambient_brand_theme"
edition = "2021"
version.workspace = true
rust-version.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ambient_api = { workspace = true }
ambient_package = { workspace = true }
ambient_shared_types = { workspace = true }
ambient_design_tokens = { git = "https://github.com/AmbientRun/DesignTokens.git" }
ambient_color = { workspace = true }
