[package]
name = "ambient_editor"
version = { workspace = true }
rust-version = { workspace = true }
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ambient_sys = { path = "../sys" }
ambient_meshes = { path = "../meshes" }
ambient_core = { path = "../core" }
ambient_ui_native = { path = "../ui_native" }
ambient_ecs = { path = "../ecs" }
ambient_network = { path = "../network" }
ambient_native_std = { path = "../native_std" }
ambient_gpu = { path = "../gpu" }
ambient_renderer = { path = "../renderer" }
ambient_rpc = { path = "../rpc" }
ambient_intent = { path = "../intent" }
ambient_ecs_editor = { path = "../ecs_editor" }
ambient_physics = { path = "../physics" }
ambient_primitives = { path = "../primitives" }
ambient_prefab = { path = "../prefab" }
ambient_decals = { path = "../decals" }
ambient_world_audio = { path = "../world_audio" }
ambient_terrain = { path = "../terrain" }
ambient_naturals = { path = "../naturals" }

physxx = { path = "../../libs/physxx" }

ambient_element = { path = "../../shared_crates/element" }
ambient_shared_types = { path = "../../shared_crates/shared_types", features = [
    "native",
] }

glam = { workspace = true }
itertools = { workspace = true }
ordered-float = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
anyhow = { workspace = true }
profiling = { workspace = true }
closure = { workspace = true }
wgpu = { workspace = true }
bytemuck = { workspace = true }
image = { workspace = true }
bitflags = { workspace = true }
tracing = { workspace = true }
parking_lot = { workspace = true }
futures-signals = { workspace = true }
derive_more = { workspace = true }

[features]
hotload-includes = [
    'ambient_native_std/hotload-includes',
    'ambient_decals/hotload-includes',
]

[target.'cfg(not(target_os = "unknown"))'.dependencies]
tokio = { workspace = true }
